const  fileInput= document.querySelector('.file-input')
const filterOptions = document.querySelector('.filter button')
const x = document.querySelector('.')
const x = document.querySelector('.')
const x = document.querySelector('.')
const x = document.querySelector('.')